apiVersion: v2
name: onecx-theme-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx theme service
keywords:
  - tenant
sources:
  - https://github.com/onecx/onecx-theme-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.41.0
    repository: oci://ghcr.io/onecx/charts